# Generated by Django 3.2.7 on 2021-09-23 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomsUsers',
            new_name='Participate',
        ),
        migrations.AlterModelOptions(
            name='participate',
            options={'verbose_name': 'dc_participate'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(through='chat.Participate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='participate',
            table='dc_participate',
        ),
    ]
