# Generated by Django 3.2.7 on 2021-09-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='status',
            field=models.CharField(choices=[('PRT', 'Participating'), ('LFT', 'Left')], default='PRT', max_length=3, verbose_name='status'),
        ),
    ]
